directive set /RSP_ETH_Node/core/ANALYZE_SHIFT -UNROLL yes
directive set /RSP_ETH_Node/core/adpcm.dtmf.add_sample:for -UNROLL yes
directive set /RSP_ETH_Node/core/adpcm_unfold -UNROLL yes
directive set /RSP_ETH_Node/core/agent.aes._addRoundKey#2:for -UNROLL yes
directive set /RSP_ETH_Node/core/agent.aes._shiftRows#1:for#2:for -UNROLL yes
directive set /RSP_ETH_Node/core/agent.aes._shiftRows#1:for#2 -UNROLL yes
directive set /RSP_ETH_Node/core/agent.aes._shiftRows#1:for#1:for -UNROLL yes
directive set /RSP_ETH_Node/core/agent.aes._shiftRows#1:for#1 -UNROLL yes
directive set /RSP_ETH_Node/core/agent.aes._shiftRows#1:for:for -UNROLL yes
directive set /RSP_ETH_Node/core/agent.aes._shiftRows#1:for -UNROLL yes
directive set /RSP_ETH_Node/core/agent.aes._subBytes#1:for -UNROLL yes
directive set /RSP_ETH_Node/core/agent.aes._addRoundKey#1:for -UNROLL yes
directive set /RSP_ETH_Node/core/agent.aes._mixColumns:for:for -UNROLL yes
directive set /RSP_ETH_Node/core/agent.aes._mixColumns:for -UNROLL yes
directive set /RSP_ETH_Node/core/agent.aes._shiftRows:for#2:for -UNROLL yes
directive set /RSP_ETH_Node/core/agent.aes._shiftRows:for#2 -UNROLL yes
directive set /RSP_ETH_Node/core/agent.aes._shiftRows:for#1:for -UNROLL yes
directive set /RSP_ETH_Node/core/agent.aes._shiftRows:for#1 -UNROLL yes
directive set /RSP_ETH_Node/core/agent.aes._shiftRows:for:for -UNROLL yes
directive set /RSP_ETH_Node/core/agent.aes._shiftRows:for -UNROLL yes
directive set /RSP_ETH_Node/core/agent.aes._subBytes:for -UNROLL yes
directive set /RSP_ETH_Node/core/agent.aes._addRoundKey:for -UNROLL yes
directive set /RSP_ETH_Node/core/agent.aes._expandKey:while:for#1 -UNROLL yes
directive set /RSP_ETH_Node/core/agent.aes._scheduleCore:for -UNROLL yes
directive set /RSP_ETH_Node/core/agent.aes._rotate:for -UNROLL yes
directive set /RSP_ETH_Node/core/agent.aes._expandKey:while:for -UNROLL yes
directive set /RSP_ETH_Node/core/agent.aes._expandKey:while -ITERATIONS 40
directive set /RSP_ETH_Node/core/agent.aes.adpcm.dec_pkt.data:rsc -MAP_TO_MODULE {[Register]}
directive set /RSP_ETH_Node/core/agent.aes._cipher_key:rsc -MAP_TO_MODULE {[Register]}
directive set /RSP_ETH_Node/agent.pkt.data.rom:rsc -MAP_TO_MODULE {[Register]}
directive set /RSP_ETH_Node/Implementation::DTMF_Algorithm::button_names.rom:rsc -MAP_TO_MODULE {[Register]}
directive set /RSP_ETH_Node/Implementation::DTMF_Algorithm::SINES.rom:rsc -MAP_TO_MODULE {[Register]}
directive set /RSP_ETH_Node/Implementation::DTMF_Algorithm::COSINES.rom:rsc -MAP_TO_MODULE {[Register]}
directive set /RSP_ETH_Node/Implementation::ADPCM_Common::INDEX_TABLE.rom:rsc -MAP_TO_MODULE {[Register]}
directive set /RSP_ETH_Node/Implementation::AES::DEFAULT_CIPHER_KEY.rom:rsc -MAP_TO_MODULE {[Register]}
directive set /RSP_ETH_Node/core/agent.aes._cipher:for -PIPELINE_INIT_INTERVAL 1
directive set /RSP_ETH_Node/core/agent.aes._expandKey:while -PIPELINE_INIT_INTERVAL 1
directive set /RSP_ETH_Node/core/agent.aes.add_key:for -UNROLL yes
directive set /RSP_ETH_Node/core/RUN -PIPELINE_INIT_INTERVAL 0

