class Memory_Map:
    LOGICAL = 0
    PHYSICAL = 1
    FLAGS = 2
    UNMAPPED = None


class TLB:
    'Used for indexing items generated by TLB_QEMU_Monitor_Parser.parse'
    PHYSICAL = 0
    FLAGS = 1


class TLB_QEMU_Monitor_Parser:
    'Parses the output of "info tlb" command of QEMU Monitor, generating a dictionary of logical to physical addresses.'

    def parse(self, tlb_file_path):
        tlb = {}
        tlb_file = open(tlb_file_path, 'r')
        for line in tlb_file:
            if ':' not in line:
                continue
            else:
                line = line.split(' ')
                assert(len(line) == 3)
                logical = line[0].replace(':', '')
                physical = line[1]
                mmu_flags = line[2]
                tlb[logical] = (physical, mmu_flags)

        tlb_file.close()

        return tlb
