#directive set /$toplevel/core/agent._expandKey:while -ITERATIONS 40
#directive set /$toplevel/core/main -PIPELINE_INIT_INTERVAL 0
#directive set /$toplevel/core/agent.add_key:for -PIPELINE_INIT_INTERVAL 0
#directive set /$toplevel/core/agent._addRoundKey#2:for -PIPELINE_INIT_INTERVAL 0
#directive set /$toplevel/core/agent._shiftRows#1:for#2 -PIPELINE_INIT_INTERVAL 0
#directive set /$toplevel/core/agent._shiftRows#1:for#1 -PIPELINE_INIT_INTERVAL 0
#directive set /$toplevel/core/agent._shiftRows#1:for -PIPELINE_INIT_INTERVAL 0
#directive set /$toplevel/core/agent._subBytes#1:for -PIPELINE_INIT_INTERVAL 0
#directive set /$toplevel/core/agent._cipher:for -PIPELINE_INIT_INTERVAL 0
#directive set /$toplevel/core/agent._addRoundKey:for -PIPELINE_INIT_INTERVAL 0
#directive set /$toplevel/core/agent._scheduleCore:for -UNROLL yes
#directive set /$toplevel/core/agent._expandKey:while -PIPELINE_INIT_INTERVAL 0
#directive set /$toplevel/core/agent._rotate:for -UNROLL yes
#directive set /$toplevel/core/agent._expandKey:while:for -UNROLL yes
#directive set /$toplevel/core/agent._expandKey:while:for#1 -UNROLL yes
#directive set /$toplevel/core/agent._shiftRows#1:for#2:for -UNROLL yes
#directive set /$toplevel/core/agent._shiftRows#1:for#1:for -UNROLL yes
#directive set /$toplevel/core/agent._shiftRows#1:for:for -UNROLL yes
#directive set /$toplevel/core/agent._mixColumns:for:for -UNROLL yes
#directive set /$toplevel/core/agent._shiftRows:for#2:for -UNROLL yes
#directive set /$toplevel/core/agent._shiftRows:for#1:for -UNROLL yes
#directive set /$toplevel/core/agent._shiftRows:for:for -UNROLL yes
#directive set /$toplevel/core/agent._addRoundKey#1:for -UNROLL yes
#directive set /$toplevel/core/agent._mixColumns:for -UNROLL yes
#directive set /$toplevel/core/agent._shiftRows:for#2 -UNROLL yes
#directive set /$toplevel/core/agent._shiftRows:for#1 -UNROLL yes
#directive set /$toplevel/core/agent._shiftRows:for -UNROLL yes
#directive set /$toplevel/core/agent._subBytes:for -UNROLL yes
#directive set /$toplevel/core/agent._addRoundKey:for -UNROLL yes
#directive set /$toplevel/core/agent._addRoundKey#2:for -UNROLL yes
#directive set /$toplevel/core/agent._subBytes#1:for -UNROLL yes
#directive set /$toplevel/core/agent._shiftRows#1:for#2 -UNROLL yes
#directive set /$toplevel/core/agent._shiftRows#1:for#1 -UNROLL yes
#directive set /$toplevel/core/agent._shiftRows#1:for -UNROLL yes
#directive set /$toplevel/core/agent._expandKey:while -UNROLL yes
#directive set /$toplevel/core/agent.add_key:for -UNROLL yes
#directive set /$toplevel/core/agent._cipher:for -UNROLL yes
#directive set /$toplevel/core/agent.adpcm.send_call:for -UNROLL yes
#directive set /$toplevel/core/agent.read_args:for -UNROLL yes
