# Connect to the board through JTAG
connect arm hw

# Uncomment the next line to program the FPGA
#fpga -f /path/to/bistream

# ps7_init.tcl provides functions to initialize the DDR controller and other
# peripherals to a default state, it's generated by Vivado
set path [file dirname [file normalize [info script]]]
source $path/ps7_init.tcl
ps7_init
ps7_post_config

# Download ELF file to Zynq's memory
dow APPLICATION_NAME

# Execute
con
